### ISSUE TITLE
Emailjs .env 

### ISSUE THREAD

**Issue by kirizarry47** [adrianhajdin/project_3D_developer_portfolio#37]
Is a .env file recommended for the Email js Service ID , Template ID and Public Key?
If so how would I import and export it ? and should the .env file go in the . gitignore file ? Id appreciate any feedback. 

Thank you!

**Comment by kalyansaxena** [comment]
Hi @kirizarry47 

we should definitely hide important keys and ids and make use of .env variables

Since we used vite tool to create the react project, we need to use a different approach to use env variables in the app than normal

1. Create .env file in the project root folder where all the config files exist
2. Don't forget to add .env to .gitignore file
3. Create your necessary env variables in your .env file
4. Now, while accessing the variables in your app, access like below
 import.meta.env.VITE_EMAILJS_SERVICE_ID
 import.meta.env.VITE_EMAILJS_TEMPLATE_ID
 
 I hope this answers your query

**Comment by kirizarry47** [comment]
You are a life saver! Thank  you
