### ISSUE TITLE
How to fix white screen, when Import {About, Hero,...} from './components';

### ISSUE THREAD

**Issue by ch4iril** [adrianhajdin/project_3D_developer_portfolio#51]
Hi Andrian

How to fix that, when I import components, screen become white, so please give me advice how to fix that

thanks

**Comment by anshadanchu368** [comment]
have same issue

**Comment by anshadanchu368** [comment]
please let me know if you found solution

**Comment by Fan-Karwanta** [comment]
I also have the same issue. I deployed the website to vercel and its perfectly fine running in desktop but in android or other mobile phones it turns the hero section to white

**Comment by yad-nick** [comment]
any luck in solving this issue. i have the same issue

**Comment by aspiluhas** [comment]
I too have the same issue

**Comment by zjian107-su** [comment]
#79 
There is a limit of how many canvas you can have for the project before memory leaks, or too much to handle. 

I assume there is an internal object queue, when you stack too many items in the container, the bottom/first canvas is crushed, that's why Hero went white. In my case, I removed some Balls until my Hero goes back. Hope this one helps!

**Comment by Hmmza-tariq** [comment]
#88 
check this out maybe it will solve your issue

**Comment by Vk2401** [comment]
I noticed a problem when viewing my mobile device and came up with the idea to hide it on mobile while keeping it visible on desktop, like Adrian.

we can mention the index value how much you what to hide in mobile


I hope this will be helpful to someone.

Tech.tsx:
```javascript
import React, { useEffect, useState } from "react";
import { BallCanvas } from "./canvas";
import { SectionWrapper } from "../hoc";
import { technologies } from "../constants";

const Tech = () => {
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    // Add a listener for changes to the screen size
    const mediaQuery = window.matchMedia("(max-width: 768px)");

    // Set the initial value of the `isMobile` state variable
    setIsMobile(mediaQuery.matches);

    // Define a callback function to handle changes to the media query
    const handleMediaQueryChange = (event) => {
      setIsMobile(event.matches);
    };

    // Add the callback function as a listener for changes to the media query
    mediaQuery.addEventListener("change", handleMediaQueryChange);

    // Remove the listener when the component is unmounted
    return () => {
      mediaQuery.removeEventListener("change", handleMediaQueryChange);
    };
  }, []);

  // Conditionally render the balls, skipping the first two on mobile
  return (
    <div className='flex flex-row flex-wrap justify-center gap-10'>
      {technologies.map((technology, index) =>
        // Use the ternary operator for conditional rendering
        isMobile && index < 4 ? null : (
          <div className='w-28 h-28' key={technology.name}>
            <BallCanvas icon={technology.icon} />
          </div>
        )
      )}
    </div>
  );
};

export default SectionWrapper(Tech, "");

**Comment by webricated** [comment]
White screen issue happens due to **unused or unrecognized "imports"**  

This is considered as error by ### .eslintrc  by default (refer solution 2 and 3 to fix eslintrc )

Solution 1 : You can comment out those unused imports till you didn't started used them.(screenshot 4)

Solution 2 : Wherever you see the red underline, use the following command in front of that line : ### {/* eslint-disable-line react/no-unknown-property */}
{This command will consider it as no error property (refer screenshot 2 attached)}

Solution 3 : If you are sure that red underlines are not an error then remove unknown property from entire file. 
_>> Hold cursor on that line >> Go to Quick fix (ctrl + .) >> Disable react/no-unknown-property for the entire file_



![Screenshot 2023-08-03 010803](https://github.com/adrianhajdin/project_3D_developer_portfolio/assets/105015109/208e727c-fb35-4358-aac5-61d6c0ec90e1)
![Screenshot 2023-08-03 010718](https://github.com/adrianhajdin/project_3D_developer_portfolio/assets/105015109/2678291a-206a-49df-9be2-4a0080ebc364)
![Screenshot 2023-08-03 010637](https://github.com/adrianhajdin/project_3D_developer_portfolio/assets/105015109/7e4342fb-1a5c-48a5-8d12-86ebc5a8bed7)
![Screenshot 2023-08-03 011054](https://github.com/adrianhajdin/project_3D_developer_portfolio/assets/105015109/ab7ab6a6-47ef-4846-a09f-7a4edfb84513)
